<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      async function main() {
        let p = new Promise((resolve, reject) => {
          reject("error");
        });
        // await の右側がPromise
        //let res = await p;
        // 2 await の右側がその他のもの
       // let res1 = await 2;
        // 3 await の右側が失敗のPromise.try catchで拾う
        try {
          let res2 = await p;
        } catch (error) {
          console.log(error);
        }
      }
      main();
    </script>
  </body>
</html>
